//@base_url=https://yoscours.alwaysdata.net
###
GET {{base_url}}/rest/users
Authorization : 1xC2yLzYn1DZgr7ET-BcMOLgOXaXRWMT

###
POST localhost:8080/rest/users
Content-Type: application/json

{
    "username": "allo",
    "password": "1234"
}

###
PUT localhost:8080/rest/users
Content-Type: application/json

{
  "username": "allo",
  "password": "1234"
}
###
POST localhost:8080/rest/auth/login
Content-Type: application/json

{
  "username": "allo",
  "password": "1234"
}

###
POST {{debug}}/rest/login
Content-Type: application/json

{
  "username": "allo",
  "password": "1234"
}

###
GET {{base_url}}/rest/technique
Authorization : _ENAFtbpLMd4VSz3pMkwdLrcAz7PgoGh

###
POST {{base_url}}/rest/technique
Content-Type: application/json

{
    "name": "suplex",
    "difficulty": "hard"
}

###
DELETE {{base_url}}/rest/technique/51